import Sidebar from './Sidebar'
import Topbar from './Topbar'
import Head from 'next//head'
import { SessionProvider } from 'next-auth/react'

export default function RootLayout({ children, page, session } : any) {
  if (session) alert('Jesteś zalogowany jako ' + session.user.name)

  return (
    <SessionProvider session={session}>
      <div className={`layout-${page}`}>
            <Head>
        <title>MessMe</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Topbar />
      {page === "chats" && <Sidebar />}
      {children}
    </div>
    </SessionProvider>
  )
}

